---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: llama-cpp-server-models
  namespace: llama
  finalizers:
    - kubernetes.io/pvc-protection
spec:
  resources:
    requests:
      storage: 30Gi
  accessModes:
    - ReadWriteOnce