name: Container Test

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - Dockerfile.*
      - model-fetch/**
      - .github/workflows/docker-test.yaml
      - requirements.txt
      - requirements-deps.txt

env:
  REGISTRY: ghcr.io

jobs:
  build:
    if: ${{ github.event.pull_request.head.repo.full_name == 'allenporter/llama-cpp-server' || github.event_name != 'pull_request' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write
    strategy:
      matrix:
        image:
        - context: .
          image: ${{ github.repository }}-simple
          dockerfile: Dockerfile.simple
        - context: .
          image: ${{ github.repository }}-cuda
          dockerfile: Dockerfile.cuda
        - context: .
          image: ${{ github.repository }}-openblas
          dockerfile: Dockerfile.openblas
        - context: .
          image: ${{ github.repository }}-clblast
          dockerfile: Dockerfile.clblast
        - context: model-fetch
          image: ${{ github.repository }}-model-fetch
          dockerfile: model-fetch/Dockerfile

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Log into registry ${{ env.REGISTRY }}
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract Docker metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ matrix.image.image }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr

    - name: Build and push Docker image
      id: build-and-push
      uses: docker/build-push-action@v6
      with:
        context: ${{ matrix.image.context }}
        push: true
        file: ${{ matrix.image.dockerfile }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
