name: Container Release

on:
  release:
    types: [published]

permissions:
  id-token: write
  contents: read
  attestations: write
  packages: write

env:
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write
    strategy:
      matrix:
        image:
        # github.repository as <account>/<repo>
        - context: .
          image: ${{ github.repository }}-simple
          dockerfile: Dockerfile.simple
        - context: .
          image: ${{ github.repository }}-cuda
          dockerfile: Dockerfile.cuda
        - context: .
          image: ${{ github.repository }}-openblas
          dockerfile: Dockerfile.openblas
        - context: .
          image: ${{ github.repository }}-clblast
          dockerfile: Dockerfile.clblast
        - context: model-fetch
          image: ${{ github.repository }}-model-fetch
          dockerfile: model-fetch/Dockerfile

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install cosign
      uses: sigstore/cosign-installer@v3
      with:
        cosign-release: 'v2.1.1'

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log into registry ${{ env.REGISTRY }}
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # Extract metadata (tags, labels) for Docker
    # https://github.com/docker/metadata-action
    - name: Extract Docker metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ matrix.image.image }}

    # Build and push Docker image with Buildx (don't push on PR)
    # https://github.com/docker/build-push-action
    - name: Build and push Docker image
      id: push
      uses: docker/build-push-action@v5
      with:
        context: ${{ matrix.image.context }}
        push: true
        file: ${{ matrix.image.dockerfile }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Generate artifact attestation
      uses: actions/attest-build-provenance@v1
      with:
        subject-name: ${{ env.REGISTRY }}/${{ matrix.image.image }}
        subject-digest: ${{ steps.push.outputs.digest }}
        push-to-registry: true
